### ISSUE TITLE
Navigating with Tab key does not work when IIS.WebManager is launched via WAC(Windows Admin Center)

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#227] opened 2018-11-30 23:27 UTC
1. Install IIS.WebManager extenstion to Windows Admin Center
2. Start WAC and open IIS feature
3. Try to navigate IIS.WebManager UI controls with tab keys

EXPECTED:

Tab key should navigate all IIS.Wemanager UI controls.

ACTUAL:

Tab key works differently comparing when IIS.WebManager is started alone without using WAC.

**Comment by shirhatti** [comment] 2019-02-05 20:28
Dupe of #231

**Closed as completed by shirhatti** 2019-02-05 20:28 UTC
Labels: bug
